### ISSUE TITLE
Extract parser class for command factory

### ISSUE THREAD

**Issue by YijinL** [se-edu/addressbook-level2#10]
Parser should take user input and construct the appropriate command object

`String -> Command`

**Comment by YijinL** [comment]
@damithc 
The all person commands require access to the `AddressBook` 
The list/delete/find/view/viewall commands  require access to the `TextUi`
This means if `Parser` is the command factory, it will have dependencies on nearly all other components.
Is this extra coupling acceptable?

**Comment by damithc** [comment]
Parser can return the command object and then the Main can feed it the extra dependencies? Does that work?

**Comment by YijinL** [comment]
Different command types require different dependencies, since Main only sees the Command interface, we will need a method in the Command interface that takes in all possible dependencies. But then some commands will not use all the arguments. I guess that's ok?

**Comment by damithc** [comment]
Yes, it's ok.
