### ISSUE TITLE
Add unit tests for Utils class

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#107]
as per title

**Comment by mauris** [comment]
Prof @damithc, one student highlighted that this was a Learning Objective in T4A6, but this issue+PR seemed to have completed the LO which the students were supposed to complete. 

See also: https://github.com/nus-cs2103-AY1617S2/addressbook-level2/blob/master/doc/LearningOutcomes.md#use-junit-to-implement-unit-tests-lo-junit
