### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#112]
Although it is not a learning outcome of this level, we can still set up for the convenience of developers and contributors.

**Comment by pyokagan** [comment]
If anyone wants to do this issue via gradle, I hacked together a small `build.gradle` file which seems to work with this repo:
```
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['test/java']
        }
    }
}

dependencies {
    testCompile 'junit:junit:4.12'
}
```

**Comment by pyokagan** [comment]
Ah, but we also need to teach Gradle how to run the stdin-stdout tests as well.

**Comment by damithc** [comment]
Yes, and that's probably non-trivial. May be an easier approach is to somehow wrap that tests into a JUnit test?

**Comment by damithc** [comment]
In fact, we can set up Travis for JUnit tests first and add the I/O test later.
