### ISSUE TITLE
Test Failing due to incorrect message

### ISSUE THREAD

**Issue by zzzzwen** [se-edu/addressbook-level2#133]
***** actual.txt
|| Enter command: || [Command entered: add [][;] p/12345 e/valid@e.mail a/vali
d, address]
|| Names should consist of letters, spaces, numbers, ', - or .
|| ===================================================
***** EXPECTED.TXT
|| Enter command: || [Command entered: add [][;] p/12345 e/valid@e.mail a/vali
d, address]
|| Person names should be spaces or alphabetic characters
|| ===================================================

Commit related to this issue : #118

**Comment by zzzzwen** [comment]
I try to fix first, I will seek help if I cannot finish

**Comment by damithc** [comment]
@zzzzwen this seems to be fixed now. Please reopen if you still have this test failure.
