### ISSUE TITLE
Limit regex to parser

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#15]
Regex is non-essential, so we should limit its use.

**Comment by YijinL** [comment]
By this you mean shift all `ARGS_FORMAT` regex patterns from the individual command classes into parser? There's no other regexes outside `Parser`, except simple uses of `String.split("\\s+")`.

**Comment by damithc** [comment]
Yes, regexes in command classes can be moved to the parser, as the regex is about the language, not the command.
Other regexes: use the dumb alternatives where possible, even the simple ones.
