### ISSUE TITLE
Parser: Give some examples of parsing without regex

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#16]
Let's give at least one example of parsing without regexes, to contrast the regex approach

**Comment by YijinL** [comment]
Can't the students refer to level 1?

The only command format differences are:
- new commands `view`, `viewall` with the exact same parsing as `delete`
- `add` command extended in level 2

Especially the level 1 `add` parsing, it's very modular and tedious. Comparing it to the level 2 `add` parsing should show the regex advantage too.

**Comment by damithc** [comment]
Yes, we can add a note in level 2 code to say the more tedious alternative is in level 1.
