### ISSUE TITLE
LO-JUnit is outdated

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#165]
The given exercise is outdated as the test code in concern has already been added.
Should be fixed before the next semester.

**Comment by PierceAndy** [comment]
Concerns:
- Currently, the Learning Outcome's exercise for JUnit tests is to create unit tests for the `Utils` class at `test/seedu/addressbook/common/UtilsTest.java`.
- However this exercise was addressed as issue #107, and closed by PR #127, as mentioned here: https://github.com/se-edu/addressbook-level2/issues/107#issuecomment-277520978
- There is no other equivalent LO for JUnit tests.
- The LO for JUnit tests serves as an introduction, and shouldn't be too complicated to implement.

Solutions:
- `UniquePersonList`, and `UniqueTagList` classes still lack JUnit tests (See: #118).
- There is an existing PR that is on hold that address this (See: #126).
- We could redirect students to create JUnit tests for either of these instead.
- The class being used for the updated LO should not be referenced as an issue.

**Comment by damithc** [comment]
Fixed in a recent commit.
