### ISSUE TITLE
Move all/most user-visible message to the Message class

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#18]
This is something to explore.
Need to consider if it is the right thing to do.

**Comment by YijinL** [comment]
Can be optional student exercise

**Comment by dezhanglee** [comment]
I have been considering working on this issue. However, after looking at all the code so far where user visible messages are printed, most of the strings are specific to the class itself. 

For example, the messages in the 'Exit' command class, like these
```
    public static final String COMMAND_WORD = "exit";

    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Exits the program.\n"
            + "Example: " + COMMAND_WORD;
    public static final String MESSAGE_EXIT_ACKNOWEDGEMENT = "Exiting Address Book as requested ...";

```

In my opinion, these kinds of class specific messages should be left to the class which uses them, for the following reasons

1. they won't be reused elsewhere, but adding them to the Message class makes it arbitrarily long.
2. For developers, (in my opinion) would be easier to leave such class specific messages in the class itself. 

Nonetheless, I think it would be a good idea to look for any reused across multiple classes to be placed in a common Message class. 

Would love to hear your thoughts regarding this.

**Comment by damithc** [comment]
Thanks for looking into this @dezhanglee 
I agree. Probably not worth the effort. Closing.
