### ISSUE TITLE
NullPointerException if viewall is used before list

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#35]
The "viewall" command, produces a Null Pointer Exception, even when there is a person at given index. To replicate the issue add a few users and close the program. Then restart and try the first command as viewall 1. However, if we try the list command before viewall the issue disappears. From the code it turns out that viewall works on the last shown list and not the stored file. I am not sure if this was intended or not.

**Comment by YijinL** [comment]
It should work on the last shown list, but should not NPE.
