### ISSUE TITLE
Remove polymorphic behavior

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level2#37]
Polymorphic behavior should be removed as it is not one of the learning outcomes at level 2.
e.g.
execute()
toString()

**Comment by damithc** [comment]
@eugenepeh can give this one a try?

**Comment by eugenepeh** [comment]
@damithc okay got it. will work on it tomorrow.

**Comment by eugenepeh** [comment]
Hello Prof @damithc ,

for this issue, if we're to remove polymorphism, is it okay to remove Parser since it is unable to return a specific data structure from the command string? Hence, I would like to proceed with `executeCommand` using the `userCommandText` directly.

**Comment by damithc** [comment]
Let me have a look and come back to you.

**Comment by damithc** [comment]
Looks like it is not easy to do in a hurry. Let's leave it for the next round.

**Comment by eugenepeh** [comment]
Closed as discussed in https://github.com/se-edu/addressbook-level2/pull/302#discussion_r165250595
