### ISSUE TITLE
AddressBook: remove master tag list

### ISSUE THREAD

**Issue by yamidark** [se-edu/addressbook-level2#383]
We keep track of a master tag list which holds all the tags in
AddressBook.

As the master tag list was deemed unnecessary and may be too 
complex for new developers to grasp, as discussed in
se-edu/addressbook-level4#753 and se-edu/addressbook-level4#794,
the master tag list has already been removed in AB4
by se-edu/addressbook-level4#824. As such, the master tag list
should also be removed for the lower level projects.

Let's remove the master tag list in AddressBook.

**Comment by damithc** [comment]
@yamidark IIRC, It is possible to link to issues across repos. e.g. `se-edu/addressbook-level4#794`
