### ISSUE TITLE
Developer Guide Typo

### ISSUE THREAD

**Issue by YezhongZ** [se-edu/addressbook-level2#411]
Under Developer Guide- Setting up - Importing the project into IntelliJ - point12 - point III

> Expand Defaults, and ensure that JUnit is selected

However, Windows 2018.2.2 version shows "Templates" instead of "Defaults"
![capture](https://user-images.githubusercontent.com/39483787/45149527-5cb46000-b1fc-11e8-9fb4-2f8271477c22.PNG)

**Comment by pyokagan** [comment]
Ah, I think you are right. Would you like to submit a PR for this?

**Comment by YezhongZ** [comment]
Sure
