### ISSUE TITLE
Broken links in [LO-JUnit] section

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level2#59]
>* [Quora post] What is the best way to avoid bugs

The link is completely missing.

> * [Web article] [The Big Cost of Software Bugs](http://www.bloomberg.com/slideshow/2012-08-03/the-big-cost-of-software-bugs.html) - An interesting post on 10 bugs that cost millions.

The link just redirects me to http://www.bloomberg.com/markets.

**Comment by damithc** [comment]
Thanks for the bug report @yamgent 
Broken link removed.
